site_name: Obsidian Theme Reference
site_url: https://bladeacer.github.io/ObsiThemeRef/
repo_url: https://github.com/bladeacer/ObsiThemeRef
repo_name: bladeacer/ObsiThemeRef
copyright: >
  Copyright &copy; bladeacer 2025
plugins:
  - search
  - meta
  - git-revision-date-localized:
      enable_creation_date: true
  - tags
extra_css:
  - stylesheets/styles.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.instant.preview
    - navigation.path
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.action.view
    - content.code.copy
  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes
    - tables
    - pymdownx.arithmatex:
        generic: true
  extra:
    tags:
      Light theme: light_theme
      Dark theme: dark_theme
      Style Settings: style_settings
      Accessibility: accessibility
      Documented: documented
      Retro: retro
      Terminal: terminal
      Minimalist: minimalist
      Custom Fonts: custom_fonts
      Callouts: callouts
      Alternate Checkboxes: alternate_checkboxes
      Checkboxes: checkboxes
      Rainbow folders: rainbow_folders
      Multiple colour schemes: multiple_colour_schemes
      Base2: base2
      Base8: base8
      base16: base16
      Gradients: gradients
      Opinionated: opinionated
      Neon: neon
      TUI: tui
      Futuristic: futuristic
      Cards layout: cards_layout
      Gnome: gnome
      GruvBox: gruvbox
      Atom: atom
      Nord: nord
      Dracula: dracula
      Catppuccin: catppuccin
      Everforest: everforest
      Material: material
      Solarized: solarized
      Neumorphism: neumorphism
      Accent: accent
      Underrated Gems: underrated_gems
      Old But Gold: old_but_gold
      New and Upcoming: new_and_upcoming
